version: '3.0'
services:
  nginx:
    container_name: nginx_container
    build:
      context: nginx
    volumes:
      - ../:/application
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - "80:80"
  php:
    container_name: php_container
    build:
      context: php
    environment:
      PHP_IDE_CONFIG: 'serverName=testWork'
    volumes:
      - ../:/application
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
